[project]
name = "compass"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "omar", email = "om039919@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=10.0.1",
    "kubernetes-asyncio>=24.2.3",
    "alembic>=1.19.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "psycopg>=3.3.4",
    "pydantic-settings>=2.14.2",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.1",
]

[project.scripts]
compass = "compass.main:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
